apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: client-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/chedjou03/Client-API-Kubernetes-ArgoCD
    targetRevision: main
    path: Dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myclient

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true